#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate

python manage.py collectstatic --noinput

exec gunicorn core.wsgi:application --bind 127.0.0.1:8000
