# Generated by Django 5.1 on 2024-08-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avialable',
            new_name='available',
        ),
    ]
