# Generated by Django 5.0.7 on 2024-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_category_name_en_category_name_uz_category_slug_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="category",
            name="slug_ru",
            field=models.SlugField(
                max_length=200, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_ru",
            field=models.SlugField(max_length=200, null=True, verbose_name="slug"),
        ),
    ]
